### ISSUE TITLE
Does this work well with unit tests?

### ISSUE THREAD

**Issue by solvingj** [Gaweph/Memoizer#5]
Python has had @cached decorator for a long time and I just tried it. Sadly, when running unit tests which send different values through cached functions, I learned that unit tests suites typically all share the same process, and in the case of python, the same "lifetime of the application". So basically, @cache makes a a function a singleton/global, which is a problem for unit tests (both parallel and sequential were affected). 

Does that all apply to this library as well?

**Comment by Gaweph** [comment]
## short answer 
In its current form it will cache the results from one test to another if you call the cached method with the same parameters.

## Long answer
I will generally mock the layer that is being cached something like `moq` and then will have a few tests in isolation to test the method itself.  The attribute works by caching the result for a given set or args, so you can call cached methods with different arguments to not trigger the cache. 

I have a working branch that is able to scope the cache inside an `xUnit` `[Fact]` or `[Theory]` and this may possibly be available at some point.  

I am also considering offering a mechanism for disabling or invalidating the cache.  But not sure how this will work yet.  Feel free to send over any `Pull Requests` for something that works if you like :)

**Comment by solvingj** [comment]
Thanks for the thoughtful answer, it all makes sense.

For posterity, I dealt with the similar situation a few different ways in the past.  The comparison I made to singleton pattern can be helpful in finding ideas on the topic because there's a lot of history for people having a similar problem using singletons and testing frameworks. 

At first, I provided a "clearcache" mechanism which is required to be run before every test.  It worked for sequential tests, but not parallel.   For parallel tests, here's what I found to work. It seems complex, but I think it's actually good. 

The `monkeypatch.setenv` method provided in python for unit tests is scoped properly when tests are run in parallel.  With that, I was able to change my cache implementation to be a "named singleton dictionary" with a simple instance name (and dictionary key) property based off an environment variable.  When the cache is checked, it checks the env var, and always pulls the appropriate value for the named instance. 

Under normal runtime scenarios where the env var is undefined, so the cache uses a hard coded default string of "default", and so the dictionary only ever has one item to write to and read from, just like a normal singleton.  However, in unit test scenarios, you get one-singleton-per-test. 

In C#, maybe there are other cross-cutting solutions you can use to implicitly feed unique values to your cache manager function.  Maybe `AppSettings` or some other global context manager supports this.  If the plumbing exists, you could create a similar/better solution instead of using environment variables as I have, which is extremely primitive.
