### ISSUE TITLE
Same method, different instance, same results

### ISSUE THREAD

**Issue by SuperJMN** [Gaweph/Memoizer#6]
I have this test to illustrate the problem. I assumed calling the same method on a different class would give different results.

While this can be interesting in some scenarios, I consider that caching scope feel more natural in a per-class fashion.

```
public class MemoizerTests
{
    [Fact]
    public void Cached_method_in_different_instances_should_return_different_results()
    {
        var i1 = new MyClass("hello");
        var i2 = new MyClass("how are you?");

        var one = i1.Get();
        var two = i2.Get();
        Assert.NotEqual(one, two);
    }

    class MyClass
    {
        private string payload;

        public MyClass(string payload)
        {
            this.payload = payload;
        }

        [Cache]
        public string Get() => payload;
    }
}
```

Does it make sense to create an option in the `CacheAttribute` to choose the scope level? 
- per-type
- per-instance

**Comment by Gaweph** [comment]
I think you're right. The assumption should be that calling on a new instance does not use the same cache.

I suppose if you wanted it to act as a singleton then you would make the class or method static so I don't think there is a need for an attribute override.

**Comment by SuperJMN** [comment]
> I think you're right. The assumption should be that calling on a new instance does not use the same cache.
> 
> I suppose if you wanted it to act as a singleton then you would make the class or method static so I don't think there is a need for an attribute override.

Hi! I'm sorry for the delay answer. I was on a trip and almost forgot this. Yes, you're right. 
BTW, I'll check the PR now.
